# Generated by Django 4.1.1 on 2022-09-20 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tshirt_cart', '0001_initial'),
        ('product_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('price_of_one', models.FloatField(default=1)),
                ('total_amount', models.FloatField(default=0)),
                ('order_count', models.ForeignKey(db_column='product_count', on_delete=django.db.models.deletion.CASCADE, related_name='number_of_prducts', to='Tshirt_cart.cart')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_list.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
