# Generated by Django 4.1.1 on 2022-09-21 07:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_list', '0001_initial'),
        ('Tshirt_cart', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='checkout',
        ),
    ]
