# Generated by Django 4.1.1 on 2022-09-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_rename_order_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='order_count',
            field=models.IntegerField(default=1),
        ),
    ]
