# Generated by Django 4.1.1 on 2022-09-20 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_payment_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment_history',
            old_name='oder_id',
            new_name='order_id',
        ),
    ]
