# Generated by Django 4.1.1 on 2022-09-20 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_list', '0001_initial'),
        ('billing', '0003_rename_oder_id_payment_history_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy_now_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('order_count', models.IntegerField(default=1)),
                ('price_of_one', models.FloatField(default=1)),
                ('total_amount', models.FloatField(default=0)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_list.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
