# Generated by Django 4.1.1 on 2022-09-21 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0001_initial'),
        ('billing', '0003_alter_checkout_order_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_payment_history',
            name='prod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product_list.products'),
        ),
    ]
