# Generated by Django 4.1.1 on 2022-09-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_order_payment_history_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_payment_history',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
