# Generated by Django 4.1.1 on 2022-09-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_payement_order_sig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement_order_sig',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
